### ISSUE TITLE
Error while installing the package.

### ISSUE THREAD

**Issue by sachdewaniavinash** [mittwald/vaulTS#34]
Hi,

I am getting the package not found error while installing the package.

<img width="654" alt="image" src="https://user-images.githubusercontent.com/85228566/167241336-ddc673f6-edaa-462a-81a4-158d6b8eea05.png">

**Comment by Lucaber** [comment]
This library is published to github packages, more info [here](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-npm-registry)
